name: Validate AsyncAPI spec

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.1
        with:
          package_json_file: example-client/package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: pnpm
          cache-dependency-path: example-client/pnpm-lock.yaml
      - name: Validate
        shell: bash
        working-directory: example-client/
        run: |
          pnpm install --frozen-lockfile
          pnpm run validate

  automerge:
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
        with:
          target: minor
          use-github-auto-merge: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
