name: Validate AsyncAPI spec

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: example-client/package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: pnpm
          cache-dependency-path: example-client/pnpm-lock.yaml
      - name: Validate
        shell: bash
        working-directory: example-client/
        run: |
          pnpm install --frozen-lockfile
          pnpm run validate
